import { ICredentialType, INodeProperties } from 'n8n-workflow';

export class TelegramUserBotApi implements ICredentialType {
  name = 'telegramUserBotApi';
  displayName = 'Telegram User Bot API';
  documentationUrl = 'https://core.telegram.org/api/obtaining_api_id';
  properties: INodeProperties[] = [
    {
      displayName: 'API ID',
      name: 'apiId',
      type: 'string',
      default: '',
      required: true,
      description: 'Your Telegram API ID from my.telegram.org',
    },
    {
      displayName: 'API Hash',
      name: 'apiHash',
      type: 'string',
      typeOptions: {
        password: true,
      },
      default: '',
      required: true,
      description: 'Your Telegram API Hash from my.telegram.org',
    },
    {
      displayName: 'Session String',
      name: 'sessionString',
      type: 'string',
      typeOptions: {
        password: true,
      },
      default: '',
      required: true,
      description: 'Session string generated by running the login script. Run: npm run login',
    },
    {
      displayName: 'Use Proxy',
      name: 'useProxy',
      type: 'boolean',
      default: false,
      description: 'Whether to use a SOCKS5 proxy',
    },
    {
      displayName: 'Proxy Host',
      name: 'proxyHost',
      type: 'string',
      default: '127.0.0.1',
      description: 'SOCKS5 proxy host/IP',
    },
    {
      displayName: 'Proxy Port',
      name: 'proxyPort',
      type: 'number',
      default: 1080,
      description: 'SOCKS5 proxy port',
    },
    {
      displayName: 'Proxy Username',
      name: 'proxyUsername',
      type: 'string',
      default: '',
      description: 'Proxy username (optional)',
    },
    {
      displayName: 'Proxy Password',
      name: 'proxyPassword',
      type: 'string',
      typeOptions: {
        password: true,
      },
      default: '',
      description: 'Proxy password (optional)',
    },
  ];
}
